# fly.toml app configuration file generated on 2025-02-06T23:14:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 25
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 25

  [[services.ports]]
    port = 465
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 587

[[vm]]
  size = 'shared-cpu-1x'
